# mcdet/models/backbones/cmnext.py

import torch
import math
import torch.nn as nn
from torch import Tensor
from collections import OrderedDict
from typing import Dict, List, Union, Optional, Tuple

from mmdet.registry import MODELS
from mmengine.model import BaseModule
from mmengine.runner import CheckpointLoader
from mcdet.models.modules.ffm import FeatureFusionModule as FFM
from mcdet.models.modules.mspa import MSPABlock
from mcdet.models.modules.ffm import FeatureRectifyModule as FRM
import functools
from functools import partial
import warnings
import torch.nn.functional as F
import numpy as np
import matplotlib
matplotlib.use('Agg')  # 비-인터랙티브 백엔드 설정
import torch.distributed as dist

try:
    import wandb
except ImportError:
    wandb = None



def load_dualpath_model(model, model_file):
    """Load pretrained model for multimodal CMNext."""
    # load raw state_dict
    if isinstance(model_file, str):
        raw_state_dict = torch.load(model_file, map_location=torch.device('cpu'))
        if 'model' in raw_state_dict.keys():
            raw_state_dict = raw_state_dict['model']
    else:
        raw_state_dict = model_file
    
    state_dict = {}
    for k, v in raw_state_dict.items():
        if k.find('patch_embed') >= 0:
            state_dict[k] = v
        elif k.find('block') >= 0:
            state_dict[k] = v
        elif k.find('norm') >= 0:
            state_dict[k] = v

    msg = model.load_state_dict(state_dict, strict=False)
    print(f"[CMNext] Pretrained model loaded: {msg}")
    del state_dict



def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class CMNextBaseModel(BaseModule):
    """Base model wrapper for CMNext backbone."""
    
    def __init__(self, 
                 backbone: str = 'CMNeXt-B0', 
                 modals: List[str] = ['rgb', 'depth', 'event', 'lidar'],
                 init_cfg: Optional[dict] = None) -> None:
        super().__init__(init_cfg=init_cfg)
        
        backbone_name, variant = backbone.split('-')
        self.backbone = eval(backbone_name)(variant, modals)
        self.modals = modals

    def _init_weights(self, m: nn.Module) -> None:
        """Initialize weights."""
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if m.bias is not None:
                nn.init.zeros_(m.bias)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out // m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                nn.init.zeros_(m.bias)
        elif isinstance(m, (nn.LayerNorm, nn.BatchNorm2d)):
            nn.init.ones_(m.weight)
            nn.init.zeros_(m.bias)

    def init_pretrained(self, pretrained: str = None) -> None:
        """Load pretrained weights."""
        if pretrained:
            if len(self.modals) > 1:
                load_dualpath_model(self.backbone, pretrained)
            else:
                checkpoint = torch.load(pretrained, map_location='cpu')
                if 'state_dict' in checkpoint.keys():
                    checkpoint = checkpoint['state_dict']
                if 'model' in checkpoint.keys():
                    checkpoint = checkpoint['model']
                msg = self.backbone.load_state_dict(checkpoint, strict=False)
                print(f"[CMNext] Single modal pretrained loaded: {msg}")


@MODELS.register_module()
class CMNextBackbone(BaseModule):
    """CMNext backbone for multimodal object detection.
    
    This backbone processes multimodal inputs (RGB, Depth, Event, LiDAR) 
    and outputs multi-scale features for detection.
    
    Args:
        backbone (str): Backbone variant, e.g., 'CMNeXt-B0', 'CMNeXt-B2'
        modals (list): List of modalities to process
        out_indices (tuple): Output indices for FPN
        frozen_stages (int): Stages to be frozen
        norm_eval (bool): Whether to set norm layers to eval mode
        pretrained (str): Path to pretrained weights
    """
    
    def __init__(self,
                 backbone: str = 'CMNeXt-B2',
                 modals: List[str] = ['rgb', 'depth', 'event', 'lidar'],
                 out_indices: Tuple[int] = (0, 1, 2, 3),
                 frozen_stages: int = -1,
                 freeze_fusion_with_stages: bool = True,
                 norm_eval: bool = False,
                 pretrained: Optional[str] = None,
                 init_cfg: Optional[dict] = None):
        
        super().__init__(init_cfg=init_cfg)
        
        self.backbone_name = backbone
        self.modals = modals
        self.out_indices = out_indices
        self.frozen_stages = frozen_stages
        self.norm_eval = norm_eval
        
        # Create CMNext base model
        self.cmnext_model = CMNextBaseModel(
            backbone=backbone, 
            modals=modals,
            init_cfg=init_cfg
        )
        
        # Determine output channels based on backbone variant
        if 'B0' in backbone or 'B1' in backbone:
            self.out_channels = [64, 128, 320, 512]  # Typical MiT-B0/B1 channels
        elif 'B2' in backbone:
            self.out_channels = [64, 128, 320, 512]  # MiT-B2 channels
        elif 'B3' in backbone:
            self.out_channels = [64, 128, 320, 512]  # MiT-B3 channels
        elif 'B4' in backbone:
            self.out_channels = [64, 128, 320, 512]  # MiT-B4 channels
        elif 'B5' in backbone:
            self.out_channels = [64, 128, 320, 512]  # MiT-B5 channels
        else:
            self.out_channels = [64, 128, 320, 512]  # Default
        
        # Load pretrained weights if provided
        if pretrained:
            self.cmnext_model.init_pretrained(pretrained)
        
        self._freeze_stages()
    
    def _freeze_stages(self, freeze_fusion_with_stages: bool = True):
        """Freeze specified stages.
        
        frozen_stages options:
        -1:  No freezing (전체 unfreeze)
         0:  Freeze stage 0 (patch_embed1, block1, norm1 + extra modules + 해당 FRM/FFM)
         1:  Freeze stages 0-1 (patch_embed1-2, block1-2, norm1-2 + extra modules + 해당 FRM/FFM)
         2:  Freeze stages 0-2 (patch_embed1-3, block1-3, norm1-3 + extra modules + 해당 FRM/FFM)
         3:  Freeze stages 0-3 (patch_embed1-4, block1-4, norm1-4 + extra modules + 해당 FRM/FFM)
         999: Freeze all including FRMs/FFMs (완전 전체 freeze)
         
        Args:
            freeze_fusion_with_stages: If True, freeze FRM/FFM along with corresponding stages
        """
        backbone = self.cmnext_model.backbone
        
        if self.frozen_stages == -1:
            # Unfreeze all - 모든 파라미터를 trainable로 설정
            print("🔥 Unfreezing all stages")
            for param in backbone.parameters():
                param.requires_grad = True
            return

        if self.frozen_stages == 999:
            # Freeze everything completely
            print("🧊 Freezing ALL parameters (including FRMs/FFMs)")
            for param in backbone.parameters():
                param.requires_grad = False
            backbone.eval()
            return
        
        # Stage별 freeze 수행
        num_stages = 4  # CMNext has 4 stages
        
        for stage_idx in range(min(self.frozen_stages + 1, num_stages)):
            print(f"🧊 Freezing stage {stage_idx}")
            
            # Freeze main patch embedding
            patch_embed_name = f"patch_embed{stage_idx + 1}"
            if hasattr(backbone, patch_embed_name):
                patch_embed = getattr(backbone, patch_embed_name)
                patch_embed.eval()
                for param in patch_embed.parameters():
                    param.requires_grad = False
                print(f"   - Frozen {patch_embed_name}")
            
            # Freeze main transformer blocks
            block_name = f"block{stage_idx + 1}"
            if hasattr(backbone, block_name):
                block = getattr(backbone, block_name)
                block.eval()
                for param in block.parameters():
                    param.requires_grad = False
                print(f"   - Frozen {block_name}")
            
            # Freeze main layer norm
            norm_name = f"norm{stage_idx + 1}"
            if hasattr(backbone, norm_name):
                norm = getattr(backbone, norm_name)
                norm.eval()
                for param in norm.parameters():
                    param.requires_grad = False
                print(f"   - Frozen {norm_name}")
            
            # Freeze extra modules (multimodal parts)
            if hasattr(backbone, 'extra_downsample_layers') and stage_idx < len(backbone.extra_downsample_layers):
                extra_downsample = backbone.extra_downsample_layers[stage_idx]
                extra_downsample.eval()
                for param in extra_downsample.parameters():
                    param.requires_grad = False
                print(f"   - Frozen extra_downsample_layers[{stage_idx}]")
            
            # Freeze extra blocks
            extra_block_name = f"extra_block{stage_idx + 1}"
            if hasattr(backbone, extra_block_name):
                extra_block = getattr(backbone, extra_block_name)
                extra_block.eval()
                for param in extra_block.parameters():
                    param.requires_grad = False
                print(f"   - Frozen {extra_block_name}")
            
            # Freeze extra norms
            extra_norm_name = f"extra_norm{stage_idx + 1}"
            if hasattr(backbone, extra_norm_name):
                extra_norm = getattr(backbone, extra_norm_name)
                extra_norm.eval()
                for param in extra_norm.parameters():
                    param.requires_grad = False
                print(f"   - Frozen {extra_norm_name}")
            
            # Freeze score predictors
            if hasattr(backbone, 'extra_score_predictor') and stage_idx < len(backbone.extra_score_predictor):
                score_predictor = backbone.extra_score_predictor[stage_idx]
                score_predictor.eval()
                for param in score_predictor.parameters():
                    param.requires_grad = False
                print(f"   - Frozen extra_score_predictor[{stage_idx}]")
            
            # Freeze corresponding FRM and FFM
            if freeze_fusion_with_stages:
                if hasattr(backbone, 'FRMs') and stage_idx < len(backbone.FRMs):
                    frm = backbone.FRMs[stage_idx]
                    frm.eval()
                    for param in frm.parameters():
                        param.requires_grad = False
                    print(f"   - Frozen FRMs[{stage_idx}]")
                
                if hasattr(backbone, 'FFMs') and stage_idx < len(backbone.FFMs):
                    ffm = backbone.FFMs[stage_idx]
                    ffm.eval()
                    for param in ffm.parameters():
                        param.requires_grad = False
                    print(f"   - Frozen FFMs[{stage_idx}]")
    
    def forward(self, x: List[torch.Tensor]) -> Tuple[torch.Tensor]:
        """Forward pass of CMNext backbone.
        
        Args:
            x: List of multimodal tensors [rgb_tensor, depth_tensor, event_tensor, lidar_tensor]
               Each tensor has shape (B, C, H, W)
        
        Returns:
            Tuple of feature tensors from different stages
        """
        # CMNext backbone expects list of multimodal inputs
        features = self.cmnext_model.backbone(x)
        
        # Convert to MMDetection standard format
        # features should be a list/dict with multi-scale outputs
        if isinstance(features, dict):
            # If features is dict with keys like '0', '1', '2', '3'
            outs = []
            for idx in self.out_indices:
                if str(idx) in features:
                    outs.append(features[str(idx)])
                elif idx in features:
                    outs.append(features[idx])
        elif isinstance(features, (list, tuple)):
            # If features is list/tuple
            outs = [features[i] for i in self.out_indices]
        else:
            raise ValueError(f"Unexpected features format: {type(features)}")
        
        return tuple(outs)
    
    def train(self, mode: bool = True):
        """Set train/eval mode."""
        super().train(mode)
        
        if mode and self.norm_eval:
            # Set norm layers to eval mode
            for m in self.modules():
                if isinstance(m, (nn.BatchNorm2d, nn.LayerNorm)):
                    m.eval()
    
    def init_weights(self):
        """Initialize weights of the backbone."""
        if self.init_cfg is None:
            # Apply custom weight initialization
            self.cmnext_model.apply(self.cmnext_model._init_weights)
        else:
            super().init_weights()



class Attention(nn.Module):
    def __init__(self, dim, head, sr_ratio):
        super().__init__()
        self.head = head
        self.sr_ratio = sr_ratio 
        self.scale = (dim // head) ** -0.5
        self.q = nn.Linear(dim, dim)
        self.kv = nn.Linear(dim, dim*2)
        self.proj = nn.Linear(dim, dim)

        if sr_ratio > 1:
            self.sr = nn.Conv2d(dim, dim, sr_ratio, sr_ratio)
            self.norm = nn.LayerNorm(dim)

    def forward(self, x: Tensor, H, W) -> Tensor:
        B, N, C = x.shape
        q = self.q(x).reshape(B, N, self.head, C // self.head).permute(0, 2, 1, 3)

        if self.sr_ratio > 1:
            x = x.permute(0, 2, 1).reshape(B, C, H, W)
            x = self.sr(x).reshape(B, C, -1).permute(0, 2, 1)
            x = self.norm(x)
            
        k, v = self.kv(x).reshape(B, -1, 2, self.head, C // self.head).permute(2, 0, 3, 1, 4)

        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)

        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        x = self.proj(x)
        return x


class DWConv(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dwconv = nn.Conv2d(dim, dim, 3, 1, 1, groups=dim)

    def forward(self, x: Tensor, H, W) -> Tensor:
        B, _, C = x.shape
        x = x.transpose(1, 2).view(B, C, H, W)
        x = self.dwconv(x)
        return x.flatten(2).transpose(1, 2)


class MLP(nn.Module):
    def __init__(self, c1, c2):
        super().__init__()
        self.fc1 = nn.Linear(c1, c2)
        self.dwconv = DWConv(c2)
        self.fc2 = nn.Linear(c2, c1)
        
    def forward(self, x: Tensor, H, W) -> Tensor:
        return self.fc2(F.gelu(self.dwconv(self.fc1(x), H, W)))


class PatchEmbed(nn.Module):
    def __init__(self, c1=3, c2=32, patch_size=7, stride=4, padding=0):
        super().__init__()
        self.proj = nn.Conv2d(c1, c2, patch_size, stride, padding)    # padding=(ps[0]//2, ps[1]//2)
        self.norm = nn.LayerNorm(c2)

    def forward(self, x: Tensor) -> Tensor:
        x = self.proj(x)
        _, _, H, W = x.shape
        x = x.flatten(2).transpose(1, 2)
        x = self.norm(x)
        return x, H, W

class PatchEmbedParallel(nn.Module):
    def __init__(self, c1=3, c2=32, patch_size=7, stride=4, padding=0, num_modals=4):
        super().__init__()
        self.proj = ModuleParallel(nn.Conv2d(c1, c2, patch_size, stride, padding))    # padding=(ps[0]//2, ps[1]//2)
        self.norm = LayerNormParallel(c2, num_modals)

    def forward(self, x: list) -> list:
        x = self.proj(x)
        _, _, H, W = x[0].shape
        x = self.norm(x)
        return x, H, W
    
class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    Copied from timm
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.
    """
    def __init__(self, p: float = None):
        super().__init__()
        self.p = p

    def forward(self, x: Tensor) -> Tensor:
        if self.p == 0. or not self.training:
            return x
        kp = 1 - self.p
        shape = (x.shape[0],) + (1,) * (x.ndim - 1)
        random_tensor = kp + torch.rand(shape, dtype=x.dtype, device=x.device)
        random_tensor.floor_()  # binarize
        return x.div(kp) * random_tensor
    
class Block(nn.Module):
    def __init__(self, dim, head, sr_ratio=1, dpr=0., is_fan=False):
        super().__init__()
        self.norm1 = nn.LayerNorm(dim)
        self.attn = Attention(dim, head, sr_ratio)
        self.drop_path = DropPath(dpr) if dpr > 0. else nn.Identity()
        self.norm2 = nn.LayerNorm(dim)
        self.mlp = MLP(dim, int(dim*4)) if not is_fan else ChannelProcessing(dim, mlp_hidden_dim=int(dim*4))

    def forward(self, x: Tensor, H, W) -> Tensor:
        x = x + self.drop_path(self.attn(self.norm1(x), H, W))
        x = x + self.drop_path(self.mlp(self.norm2(x), H, W))
        return x


class ChannelProcessing(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, attn_drop=0., drop_path=0., mlp_hidden_dim=None, norm_layer=nn.LayerNorm):
        super().__init__()
        assert dim % num_heads == 0, f"dim {dim} should be divided by num_heads {num_heads}."
        self.dim = dim
        self.num_heads = num_heads

        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.mlp_v = MLP(dim, mlp_hidden_dim)
        self.norm_v = norm_layer(dim)

        self.q = nn.Linear(dim, dim, bias=qkv_bias)
        self.pool = nn.AdaptiveAvgPool2d((None, 1))
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x, H, W, atten=None):
        B, N, C = x.shape

        v = x.reshape(B, N, self.num_heads, C // self.num_heads).permute(0, 2, 1, 3)
        q = self.q(x).reshape(B, N, self.num_heads, C // self.num_heads).permute(0, 2, 1, 3)
        k = x.reshape(B, N, self.num_heads,  C // self.num_heads).permute(0, 2, 1, 3)

        q = q.softmax(-2).transpose(-1,-2)
        _, _, Nk, Ck  = k.shape
        k = k.softmax(-2)
        k = torch.nn.functional.avg_pool2d(k, (1, Ck))
        
        attn = self.sigmoid(q @ k)

        Bv, Hd, Nv, Cv = v.shape
        v = self.norm_v(self.mlp_v(v.transpose(1, 2).reshape(Bv, Nv, Hd*Cv), H, W)).reshape(Bv, Nv, Hd, Cv).transpose(1, 2)
        x = (attn * v.transpose(-1, -2)).permute(0, 3, 1, 2).reshape(B, N, C)
        return x 


class PredictorConv(nn.Module):
    def __init__(self, embed_dim=384, num_modals=4):
        super().__init__()
        self.num_modals = num_modals
        self.score_nets = nn.ModuleList([nn.Sequential(
            nn.Conv2d(embed_dim, embed_dim, 3, 1, 1, groups=(embed_dim)),
            nn.Conv2d(embed_dim, 1, 1),
            nn.Sigmoid()
        )for _ in range(num_modals)])

    def forward(self, x):
        B, C, H, W = x[0].shape
        x_ = [torch.zeros((B, 1, H, W)) for _ in range(self.num_modals)]
        for i in range(self.num_modals):
            x_[i] = self.score_nets[i](x[i])
        return x_

class ModuleParallel(nn.Module):
    def __init__(self, module):
        super(ModuleParallel, self).__init__()
        self.module = module

    def forward(self, x_parallel):
        return [self.module(x) for x in x_parallel]

class ConvLayerNorm(nn.Module):
    """Channel first layer norm
    """
    def __init__(self, normalized_shape, eps=1e-6) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(normalized_shape))
        self.bias = nn.Parameter(torch.zeros(normalized_shape))
        self.eps = eps

    def forward(self, x: Tensor) -> Tensor:
        u = x.mean(1, keepdim=True)
        s = (x - u).pow(2).mean(1, keepdim=True)
        x = (x - u) / torch.sqrt(s + self.eps)
        x = self.weight[:, None, None] * x + self.bias[:, None, None]
        return x

class LayerNormParallel(nn.Module):
    def __init__(self, num_features, num_modals=4):
        super(LayerNormParallel, self).__init__()
        # self.num_modals = num_modals
        for i in range(num_modals):
            setattr(self, 'ln_' + str(i), ConvLayerNorm(num_features, eps=1e-6))

    def forward(self, x_parallel):
        return [getattr(self, 'ln_' + str(i))(x) for i, x in enumerate(x_parallel)]


cmnext_settings = {
    # 'B0': [[32, 64, 160, 256], [2, 2, 2, 2]],
    # 'B1': [[64, 128, 320, 512], [2, 2, 2, 2]],
    'B2': [[64, 128, 320, 512], [3, 4, 6, 3]],
    # 'B3': [[64, 128, 320, 512], [3, 4, 18, 3]],
    'B4': [[64, 128, 320, 512], [3, 8, 27, 3]],
    'B5': [[64, 128, 320, 512], [3, 6, 40, 3]]
}


class CMNeXt(nn.Module):
    def __init__(self, model_name: str = 'B0', modals: list = ['rgb', 'depth', 'event', 'lidar']):
        super().__init__()
        self.iter = 0
        assert model_name in cmnext_settings.keys(), f"Model name should be in {list(cmnext_settings.keys())}"
        embed_dims, depths = cmnext_settings[model_name]
        extra_depths = depths 
        self.modals = modals[1:] if len(modals)>1 else []  
        self.num_modals = len(self.modals)
        drop_path_rate = 0.1
        self.channels = embed_dims
        norm_cfg = dict(type='BN', requires_grad=True)

        # patch_embed
        self.patch_embed1 = PatchEmbed(3, embed_dims[0], 7, 4, 7//2)
        self.patch_embed2 = PatchEmbed(embed_dims[0], embed_dims[1], 3, 2, 3//2)
        self.patch_embed3 = PatchEmbed(embed_dims[1], embed_dims[2], 3, 2, 3//2)
        self.patch_embed4 = PatchEmbed(embed_dims[2], embed_dims[3], 3, 2, 3//2)
   
        if self.num_modals > 0:
            self.extra_downsample_layers = nn.ModuleList([
                PatchEmbedParallel(3, embed_dims[0], 7, 4, 7//2, self.num_modals),
                *[PatchEmbedParallel(embed_dims[i], embed_dims[i+1], 3, 2, 3//2, self.num_modals) for i in range(3)]
            ])
        if self.num_modals > 1:
            self.extra_score_predictor = nn.ModuleList([PredictorConv(embed_dims[i], self.num_modals) for i in range(len(depths))])

        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, sum(depths))]
        
        cur = 0
        self.block1 = nn.ModuleList([Block(embed_dims[0], 1, 8, dpr[cur+i]) for i in range(depths[0])])
        self.norm1 = nn.LayerNorm(embed_dims[0])
        if self.num_modals > 0:
            self.extra_block1 = nn.ModuleList([MSPABlock(embed_dims[0], mlp_ratio=8, drop_path=dpr[cur+i], norm_cfg=norm_cfg) for i in range(extra_depths[0])]) # --- MSPABlock
            self.extra_norm1 = ConvLayerNorm(embed_dims[0])
            
        cur += depths[0]
        self.block2 = nn.ModuleList([Block(embed_dims[1], 2, 4, dpr[cur+i]) for i in range(depths[1])])
        self.norm2 = nn.LayerNorm(embed_dims[1])
        if self.num_modals > 0:
            self.extra_block2 = nn.ModuleList([MSPABlock(embed_dims[1], mlp_ratio=8, drop_path=dpr[cur+i], norm_cfg=norm_cfg) for i in range(extra_depths[1])])
            self.extra_norm2 = ConvLayerNorm(embed_dims[1])

        cur += depths[1]
        self.block3 = nn.ModuleList([Block(embed_dims[2], 5, 2, dpr[cur+i]) for i in range(depths[2])])
        self.norm3 = nn.LayerNorm(embed_dims[2])
        if self.num_modals > 0:
            self.extra_block3 = nn.ModuleList([MSPABlock(embed_dims[2], mlp_ratio=4, drop_path=dpr[cur+i], norm_cfg=norm_cfg) for i in range(extra_depths[2])])
            self.extra_norm3 = ConvLayerNorm(embed_dims[2])

        cur += depths[2]
        self.block4 = nn.ModuleList([Block(embed_dims[3], 8, 1, dpr[cur+i]) for i in range(depths[3])])
        self.norm4 = nn.LayerNorm(embed_dims[3])
        if self.num_modals > 0:
            self.extra_block4 = nn.ModuleList([MSPABlock(embed_dims[3], mlp_ratio=4, drop_path=dpr[cur+i], norm_cfg=norm_cfg) for i in range(extra_depths[3])])
            self.extra_norm4 = ConvLayerNorm(embed_dims[3])

        if self.num_modals > 0:
            num_heads = [1,2,5,8]
            self.FRMs = nn.ModuleList([
                FRM(dim=embed_dims[0], reduction=1),
                FRM(dim=embed_dims[1], reduction=1),
                FRM(dim=embed_dims[2], reduction=1),
                FRM(dim=embed_dims[3], reduction=1)])
            self.FFMs = nn.ModuleList([
                FFM(dim=embed_dims[0], reduction=1, num_heads=num_heads[0], norm_layer=nn.BatchNorm2d),
                FFM(dim=embed_dims[1], reduction=1, num_heads=num_heads[1], norm_layer=nn.BatchNorm2d),
                FFM(dim=embed_dims[2], reduction=1, num_heads=num_heads[2], norm_layer=nn.BatchNorm2d),
                FFM(dim=embed_dims[3], reduction=1, num_heads=num_heads[3], norm_layer=nn.BatchNorm2d)])

    def tokenselect(self, x_ext, module):    
        x_scores = module(x_ext)                            #score 에서 token을 선택
        for i in range(len(x_ext)):
            x_ext[i] = x_scores[i] * x_ext[i] + x_ext[i]
        stacked_x_ext = torch.stack(x_ext, dim=1) 
        x_f, x_f_indices = torch.max(stacked_x_ext, dim=1) 
        return x_f, x_scores, x_f_indices
     
    def forward(self, x: list) -> list:
        modal_list = ["depth", "ir", "lidar"]
        x_cam = x[0]        
        if self.num_modals > 0:
            x_ext = x[1:]
        B = x_cam.shape[0]
        outs = []
        # stage 1
        print("[INFO] Stage1")
        x_cam, H, W = self.patch_embed1(x_cam)
        for blk in self.block1:
            x_cam = blk(x_cam, H, W)
        x1_cam = self.norm1(x_cam).reshape(B, H, W, -1).permute(0, 3, 1, 2)
        if self.num_modals > 0:
            x_ext, _, _ = self.extra_downsample_layers[0](x_ext)
            x_f, x_scores, winner_indices = self.tokenselect(x_ext, self.extra_score_predictor[0]) if self.num_modals > 1 else (x_ext[0], None)    
            for blk in self.extra_block1:
                x_f = blk(x_f)
            x1_f_ = self.extra_norm1(x_f)
            x1_cam, x1_f = self.FRMs[0](x1_cam, x1_f_)
            x_fused = self.FFMs[0](x1_cam, x1_f)
            
            if x_scores is not None and self.training is False:
                rank = dist.get_rank() if dist.is_available() and dist.is_initialized() else -1
                if rank == 0 or rank == -1:
                    import wandb
                    a_dict = {}
                    for i, modal in enumerate(modal_list):
                        if i < len(x_scores):
                            a_dict[f"rank_{rank}_stage1_score_{modal}"] = x_scores[i].mean().item()
                    wandb.log(a_dict)
                    if self.iter % 1000 ==0:
                        ppx_save_path = f"./wandb_img_PPx_rank{rank}.png"
                        vis_tensor_single_batch_grid(x1_f_, batch=0, save_path=ppx_save_path)
                        wandb.log({"stage1_PPX": wandb.Image(ppx_save_path)})
                        frm_save_path = f"./wandb_img_FRM_rank{rank}.png"
                        vis_tensor_single_batch_grid(x1_cam, batch=0, save_path=frm_save_path)
                        wandb.log({"stage1_FRM": wandb.Image(frm_save_path)})
                        ffm_save_path = f"./wandb_img_FFM_rank{rank}.png"
                        vis_tensor_single_batch_grid(x_fused, batch=0, save_path=ffm_save_path)
                        wandb.log({"stage1_FFM": wandb.Image(ffm_save_path)})
                        indice_save_path = f'./wandb_img_IND_rank{rank}.png'
                        visualize_channel_winners(
                            winner_indices, modal_list, indice_save_path, title=f'stage1_winner_indices_rank{rank}'
                        )
                        wandb.log({"stage1_winner_indices": wandb.Image(indice_save_path)})

            outs.append(x_fused)
            x_ext = [x_.reshape(B, H, W, -1).permute(0, 3, 1, 2) + x1_f for x_ in x_ext] if self.num_modals > 1 else [x1_f]
        else:
            outs.append(x1_cam)
        print("[INFO] Stage2")

        # stage 2
        x_cam, H, W = self.patch_embed2(x1_cam)
        for blk in self.block2:
            x_cam = blk(x_cam, H, W)
        x2_cam = self.norm2(x_cam).reshape(B, H, W, -1).permute(0, 3, 1, 2)
        if self.num_modals > 0:
            x_ext, _, _ = self.extra_downsample_layers[1](x_ext)
            x_f, x_scores, winner_indices = self.tokenselect(x_ext, self.extra_score_predictor[1]) if self.num_modals > 1 else (x_ext[0], None)    
            for blk in self.extra_block2:
                x_f = blk(x_f)
            x2_f_ = self.extra_norm2(x_f)
            x2_cam, x2_f = self.FRMs[1](x2_cam, x2_f_)
            x_fused = self.FFMs[1](x2_cam, x2_f)
            if x_scores is not None and self.training is False:
                rank = dist.get_rank() if dist.is_available() and dist.is_initialized() else -1
                if rank == 0 or rank == -1:
                    import wandb
                    a_dict = {}
                    for i, modal in enumerate(modal_list):
                        if i < len(x_scores):
                            a_dict[f"rank_{rank}_stage2_score_{modal}"] = x_scores[i].mean().item()
                    wandb.log(a_dict)
    
                    if self.iter % 500 ==0:
                        ppx_save_path = f"./wandb_img_PPx_rank{rank}.png"
                        vis_tensor_single_batch_grid(x1_f_, batch=0, save_path=ppx_save_path)
                        wandb.log({"stage2_PPX": wandb.Image(ppx_save_path)})
                        frm_save_path = f"./wandb_img_FRM_rank{rank}.png"
                        vis_tensor_single_batch_grid(x1_cam, batch=0, save_path=frm_save_path)
                        wandb.log({"stage2_FRM": wandb.Image(frm_save_path)})
                        ffm_save_path = f"./wandb_img_FFM_rank{rank}.png"
                        vis_tensor_single_batch_grid(x_fused, batch=0, save_path=ffm_save_path)
                        wandb.log({"stage2_FFM": wandb.Image(ffm_save_path)})
                        indice_save_path = f'./wandb_img_IND_rank{rank}.png'
                        visualize_channel_winners(
                            winner_indices, modal_list, indice_save_path, title=f'stage2_winner_indices_rank{rank}'
                        )
                        wandb.log({"stage2_winner_indices": wandb.Image(indice_save_path)})

            outs.append(x_fused)
            x_ext = [x_.reshape(B, H, W, -1).permute(0, 3, 1, 2) + x2_f for x_ in x_ext] if self.num_modals > 1 else [x2_f]
        else:
            outs.append(x2_cam)

        # stage 3
        print("[INFO] Stage3")
        x_cam, H, W = self.patch_embed3(x2_cam)
        for blk in self.block3:
            x_cam = blk(x_cam, H, W)
        x3_cam = self.norm3(x_cam).reshape(B, H, W, -1).permute(0, 3, 1, 2)
        if self.num_modals > 0:
            x_ext, _, _ = self.extra_downsample_layers[2](x_ext)
            x_f, x_scores, winner_indices = self.tokenselect(x_ext, self.extra_score_predictor[2]) if self.num_modals > 1 else (x_ext[0], None)    
            for blk in self.extra_block3:
                x_f = blk(x_f)
            x3_f_ = self.extra_norm3(x_f)
            x3_cam, x3_f = self.FRMs[2](x3_cam, x3_f_)
            x_fused = self.FFMs[2](x3_cam, x3_f)
            if x_scores is not None and self.training is False:
                rank = dist.get_rank() if dist.is_available() and dist.is_initialized() else -1
                if rank == 0 or rank == -1:
                    a_dict = {}
                    for i, modal in enumerate(modal_list):
                        if i < len(x_scores):
                            a_dict[f"rank_{rank}_stage3_score_{modal}"] = x_scores[i].mean().item()
                    wandb.log(a_dict)
                    if self.iter % 500 ==0:
                        ppx_save_path = f"./wandb_img_PPx_rank{rank}.png"
                        vis_tensor_single_batch_grid(x1_f_, batch=0, save_path=ppx_save_path)
                        wandb.log({"stage3_PPX": wandb.Image(ppx_save_path)})
                        frm_save_path = f"./wandb_img_FRM_rank{rank}.png"
                        vis_tensor_single_batch_grid(x1_cam, batch=0, save_path=frm_save_path)
                        wandb.log({"stage3_FRM": wandb.Image(frm_save_path)})
                        ffm_save_path = f"./wandb_img_FFM_rank{rank}.png"
                        vis_tensor_single_batch_grid(x_fused, batch=0, save_path=ffm_save_path)
                        wandb.log({"stage3_FFM": wandb.Image(ffm_save_path)})
                        indice_save_path = f'./wandb_img_IND_rank{rank}.png'
                        visualize_channel_winners(
                            winner_indices, modal_list, indice_save_path, title=f'stage3_winner_indices_rank{rank}'
                        )
                        wandb.log({"stage3_winner_indices": wandb.Image(indice_save_path)})
            outs.append(x_fused)
            x_ext = [x_.reshape(B, H, W, -1).permute(0, 3, 1, 2) + x3_f for x_ in x_ext] if self.num_modals > 1 else [x3_f]
        else:
            outs.append(x3_cam)

        # stage 4
        print("[INFO] Stage4")
        x_cam, H, W = self.patch_embed4(x3_cam)
        for blk in self.block4:
            x_cam = blk(x_cam, H, W)
        x4_cam = self.norm4(x_cam).reshape(B, H, W, -1).permute(0, 3, 1, 2)
        if self.num_modals > 0:
            x_ext, _, _ = self.extra_downsample_layers[3](x_ext)
            x_f, x_scores, winner_indices = self.tokenselect(x_ext, self.extra_score_predictor[3]) if self.num_modals > 1 else (x_ext[0], None)    
            for blk in self.extra_block4:
                x_f = blk(x_f)
            
            x4_f_ = self.extra_norm4(x_f)
            x4_cam, x4_f = self.FRMs[3](x4_cam, x4_f_)
            x_fused = self.FFMs[3](x4_cam, x4_f)
            if x_scores is not None and self.training is False:
                rank = dist.get_rank() if dist.is_available() and dist.is_initialized() else -1
                if rank == 0 or rank == -1:
                    a_dict = {}
                    for i, modal in enumerate(modal_list):
                        if i < len(x_scores):
                            a_dict[f"rank_{rank}_stage4_score_{modal}"] = x_scores[i].mean().item()
                    wandb.log(a_dict)
                    if self.iter % 500 ==0:
                        ppx_save_path = f"./wandb_img_PPx_rank{rank}.png"
                        vis_tensor_single_batch_grid(x1_f_, batch=0, save_path=ppx_save_path)
                        wandb.log({"stage4_PPX": wandb.Image(ppx_save_path)})
                        frm_save_path = f"./wandb_img_FRM_rank{rank}.png"
                        vis_tensor_single_batch_grid(x1_cam, batch=0, save_path=frm_save_path)
                        wandb.log({"stage4_FRM": wandb.Image(frm_save_path)})
                        ffm_save_path = f"./wandb_img_FFM_rank{rank}.png"
                        vis_tensor_single_batch_grid(x_fused, batch=0, save_path=ffm_save_path)
                        wandb.log({"stage4_FFM": wandb.Image(ffm_save_path)})
                        indice_save_path = f'./wandb_img_IND_rank{rank}.png'
                        visualize_channel_winners(
                            winner_indices, modal_list, indice_save_path, title=f'stage4_winner_indices_rank{rank}'
                        )
                        wandb.log({"stage4_winner_indices": wandb.Image(indice_save_path)})
            outs.append(x_fused)
        else:
            outs.append(x4_cam)

        return outs

def vis_tensor_grid(tensor: torch.Tensor, batch=0, save_path='tmp_grid_colormap.png'):
    """
    Visualize all 12 channels of a tensor in a 4x3 grid with Grad-CAM style colormap (jet).
    
    Args:
        tensor (torch.Tensor): Input tensor of shape (C, H, W) or (B, C, H, W).
        batch (int): Batch index if tensor has a batch dimension.
        save_path (str): Path to save the grid image.
    """
    import matplotlib.pyplot as plt
    # Handle batch dimension
    if tensor.dim() == 4:  # (B, C, H, W)
        tensor = tensor[batch]
    
    C, H, W = tensor.shape
    assert C > 12, "Tensor must have 12 channels"
    
    tensor_np = tensor.detach().cpu().numpy()
    
    # Normalize each channel to [0,1] for better colormap visualization
    tensor_np = (tensor_np - tensor_np.min(axis=(1,2), keepdims=True)) / \
                (tensor_np.max(axis=(1,2), keepdims=True) - tensor_np.min(axis=(1,2), keepdims=True) + 1e-8)
    
    # Create 4x3 subplot
    fig, axes = plt.subplots(3, 4, figsize=(16, 12))
    for i in range(12):
        r, c = divmod(i, 4)
        axes[r, c].imshow(tensor_np[i], cmap='jet')
        axes[r, c].axis('off')
        axes[r, c].set_title(f'Channel {i}')
    
    plt.tight_layout()
    plt.savefig(save_path)
    plt.close()
    print(f"Saved 12-channel Grad-CAM style grid to {save_path}")
    
    
    
def vis_tensor_single_batch(tensor:torch.tensor, batch=0, save_path='vis_tensor.png'):
    import matplotlib.pyplot as plt
    import numpy as np
    tensor = tensor[batch]
    if len(tensor.shape) != 3:
        assert "Tensor must have 3 dimensions (C, H, W)"
    C, H, W = tensor.shape
    tensor_np = tensor.detach().cpu().numpy()
    tensor_np = (tensor_np - tensor_np.min()) / (tensor_np.max() - tensor_np.min() + 1e-8)  # Normalize to [0, 1]
    tensor_np = (tensor_np * 255).astype(np.uint8)  # Convert to uint8 for visualization
    # Create a grid of images
    fig, ax = plt.subplots(figsize=(12, 8))
    ax.imshow(tensor_np.transpose(1, 2, 0))  # Transpose to (H, W, C)
    ax.axis('off')
    plt.tight_layout()
    plt.savefig(save_path)
    plt.close()
    
    
def vis_tensor_single_batch_grid(tensor:torch.tensor, batch=0, save_path='vis_tensor.png'):
    import matplotlib.pyplot as plt
    import numpy as np
    
    tensor = tensor[batch]
    tensor_np = tensor.detach().cpu().numpy()
    C, H, W = tensor_np.shape
    ncols = int(np.ceil(np.sqrt(C)))
    nrows = int(np.ceil(C / ncols))
    fig, axes = plt.subplots(nrows, ncols, figsize=(3*ncols, 3*nrows))
    axes = axes.flatten()
    
    for i in range(C):
        ch = tensor_np[i]
        axes[i].imshow(ch, cmap='jet')
        axes[i].axis('off')
        axes[i].set_title(f"Channel {i}", fontsize=10)
    
    # Hide unused axes
    for j in range(C, len(axes)):
        axes[j].axis('off')
    
    plt.tight_layout()
    plt.savefig(save_path)
    plt.close()
    print(f"Saved tensor visualization grid to {save_path}")
    

# mcdet/models/backbones/cmnext.py 파일 하단에 추가

def visualize_channel_winners(
    winner_indices: torch.Tensor,
    modality_names: List[str],
    save_path: str = 'feature_map.png',
    title: str = 'Modality Winner Map per Channel',
    batch_idx: int = 0
):
    """
    (B, C, H, W) 형태의 다중 채널 '승자 인덱스' 맵을 입력받아,
    각 채널을 R,G,B로 색칠된 이미지로 변환하고 그리드 형태로 시각화합니다.
    """
    import matplotlib.pyplot as plt
    import numpy as np

    # 4D 텐서(B, C, H, W)일 경우, 지정된 배치만 선택
    if winner_indices.dim() == 4:
        winner_indices = winner_indices[batch_idx]
    
    indices_np = winner_indices.detach().cpu().numpy()
    C, H, W = indices_np.shape

    # 그리드 크기 계산 (예: 64채널 -> 8x8)
    ncols = int(np.ceil(np.sqrt(C)))
    nrows = int(np.ceil(C / ncols))

    fig, axes = plt.subplots(nrows, ncols, figsize=(2 * ncols, 2 * nrows))
    axes = axes.flatten()
    
    # 전체 제목 추가 (범례 역할 포함)
    legend_str = "Colors  :  "
    for i, name in enumerate(modality_names):
        if i < 3:
            legend_str += f"{['R', 'G', 'B'][i]}:{name}  "
    fig.suptitle(f'{title}\n({legend_str.strip()})', fontsize=16)

    # ✅ [핵심] 컬러 팔레트를 미리 정의
    color_palette = np.array([
        [255, 0, 0],   # 인덱스 0 (Red)
        [0, 255, 0],   # 인덱스 1 (Green)
        [0, 0, 255],   # 인덱스 2 (Blue)
        [255, 255, 0]  # 인덱스 3 (Yellow)
    ], dtype=np.uint8)
    
    for i in range(C):
        # i번째 채널의 인덱스 맵을 가져옴. Shape: (H, W)
        index_map = indices_np[i]
        
        # ✅ [핵심] (H, W) 인덱스 맵을 (H, W, 3) RGB 이미지로 변환
        rgb_image = color_palette[index_map]
        
        ax = axes[i]
        # ✅ [핵심] cmap이 아닌, 변환된 RGB 이미지를 직접 그림
        ax.imshow(rgb_image)
        ax.axis('off')
        ax.set_title(f"Ch: {i}", fontsize=10)
    
    # 사용하지 않는 나머지 subplot 숨기기
    for j in range(C, len(axes)):
        axes[j].axis('off')
    
    plt.tight_layout(rect=[0, 0, 1, 0.92]) # suptitle과 겹치지 않도록 조정
    plt.savefig(save_path)
    plt.close(fig)
    print(f"Saved channel winner visualization to {save_path}")


