# mcdet/models/backbones/cmnextp.py

import torch
import math
import torch.nn as nn
from torch import Tensor
from collections import OrderedDict
from typing import Dict, List, Union, Optional, Tuple

from mmdet.registry import MODELS
from mmengine.model import BaseModule
from mmengine.runner import CheckpointLoader
from mcdet.models.modules.ffm import FeatureFusionModule as FFM
from mcdet.models.modules.mspa import MSPABlock
from mcdet.models.modules.ffm import FeatureRectifyModule as FRM
import functools
from functools import partial
import warnings
import torch.nn.functional as F
import numpy as np
import matplotlib
matplotlib.use('Agg')  # 비-인터랙티브 백엔드 설정
import torch.distributed as dist

try:
    import wandb
except ImportError:
    wandb = None
    

class SpatialAttentionModule(nn.Module):
    """
    Computes a spatial attention map for self-scoring.
    This helps to identify regions with strong signals vs. no signals (e.g., black areas in IR).
    """
    def __init__(self, in_channels: int):
        super().__init__()
        # 채널 정보를 1개로 압축하기 위한 1x1 컨볼루션
        self.conv = nn.Conv2d(in_channels, 1, kernel_size=1, stride=1, padding=0)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x: Tensor) -> Tensor:
        """
        Args:
            x (Tensor): Input feature map of shape (B, C, H, W).
        Returns:
            Tensor: Spatial attention map of shape (B, 1, H, W).
        """
        # (B, C, H, W) -> (B, 1, H, W)
        attention_map = self.conv(x)
        return self.sigmoid(attention_map)

def load_dualpath_model(model, model_file):
    """Load pretrained model for multimodal CMNext."""
    # load raw state_dict
    if isinstance(model_file, str):
        raw_state_dict = torch.load(model_file, map_location=torch.device('cpu'))
        if 'model' in raw_state_dict.keys():
            raw_state_dict = raw_state_dict['model']
    else:
        raw_state_dict = model_file
    
    state_dict = {}
    for k, v in raw_state_dict.items():
        if k.find('patch_embed') >= 0:
            state_dict[k] = v
        elif k.find('block') >= 0:
            state_dict[k] = v
        elif k.find('norm') >= 0:
            state_dict[k] = v

    msg = model.load_state_dict(state_dict, strict=False)
    print(f"[CMNext] Pretrained model loaded: {msg}")
    del state_dict

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class CMNextBaseModel(BaseModule):
    """Base model wrapper for CMNext backbone."""
    
    def __init__(self, 
                 backbone: str = 'CMNeXt-B0', 
                 modals: List[str] = ['rgb', 'depth', 'event', 'lidar'],
                 init_cfg: Optional[dict] = None) -> None:
        super().__init__(init_cfg=init_cfg)
        
        backbone_name, variant = backbone.split('-')
        self.backbone = eval(backbone_name)(variant, modals)
        self.modals = modals

    def _init_weights(self, m: nn.Module) -> None:
        """Initialize weights."""
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if m.bias is not None:
                nn.init.zeros_(m.bias)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out // m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                nn.init.zeros_(m.bias)
        elif isinstance(m, (nn.LayerNorm, nn.BatchNorm2d)):
            nn.init.ones_(m.weight)
            nn.init.zeros_(m.bias)

    def init_pretrained(self, pretrained: str = None) -> None:
        """Load pretrained weights."""
        if pretrained:
            if len(self.modals) > 1:
                load_dualpath_model(self.backbone, pretrained)
            else:
                checkpoint = torch.load(pretrained, map_location='cpu')
                if 'state_dict' in checkpoint.keys():
                    checkpoint = checkpoint['state_dict']
                if 'model' in checkpoint.keys():
                    checkpoint = checkpoint['model']
                msg = self.backbone.load_state_dict(checkpoint, strict=False)
                print(f"[CMNext] Single modal pretrained loaded: {msg}")


@MODELS.register_module()
class CMNeXtPSPBackbone(BaseModule):
    """CMNext backbone for multimodal object detection.
    
    This backbone processes multimodal inputs (RGB, Depth, Event, LiDAR) 
    and outputs multi-scale features for detection.
    
    Args:
        backbone (str): Backbone variant, e.g., 'CMNeXt-B0', 'CMNeXt-B2'
        modals (list): List of modalities to process
        out_indices (tuple): Output indices for FPN
        frozen_stages (int): Stages to be frozen
        norm_eval (bool): Whether to set norm layers to eval mode
        pretrained (str): Path to pretrained weights
    """
    
    def __init__(self,
                 backbone: str = 'CMNeXtPSP-B2',
                 modals: List[str] = ['rgb', 'depth', 'event', 'lidar'],
                 out_indices: Tuple[int] = (0, 1, 2, 3),
                 frozen_stages: int = -1,
                 freeze_fusion_with_stages: bool = True,
                 norm_eval: bool = False,
                 pretrained: Optional[str] = None,
                 init_cfg: Optional[dict] = None):
        
        super().__init__(init_cfg=init_cfg)
        
        self.backbone_name = backbone
        self.modals = modals
        self.out_indices = out_indices
        self.frozen_stages = frozen_stages
        self.norm_eval = norm_eval
        
        # Create CMNext base model
        self.cmnext_model = CMNextBaseModel(
            backbone=backbone, 
            modals=modals,
            init_cfg=init_cfg
        )
        
        # Determine output channels based on backbone variant
        if 'B0' in backbone or 'B1' in backbone:
            self.out_channels = [64, 128, 320, 512]  # Typical MiT-B0/B1 channels
        elif 'B2' in backbone:
            self.out_channels = [64, 128, 320, 512]  # MiT-B2 channels
        elif 'B3' in backbone:
            self.out_channels = [64, 128, 320, 512]  # MiT-B3 channels
        elif 'B4' in backbone:
            self.out_channels = [64, 128, 320, 512]  # MiT-B4 channels
        elif 'B5' in backbone:
            self.out_channels = [64, 128, 320, 512]  # MiT-B5 channels
        else:
            self.out_channels = [64, 128, 320, 512]  # Default
        
        # Load pretrained weights if provided
        if pretrained:
            self.cmnext_model.init_pretrained(pretrained)
        
        self._freeze_stages()
    
    def _freeze_stages(self, freeze_fusion_with_stages: bool = True):
        """Freeze specified stages.
        
        frozen_stages options:
        -1:  No freezing (전체 unfreeze)
         0:  Freeze stage 0 (patch_embed1, block1, norm1 + extra modules + 해당 FRM/FFM)
         1:  Freeze stages 0-1 (patch_embed1-2, block1-2, norm1-2 + extra modules + 해당 FRM/FFM)
         2:  Freeze stages 0-2 (patch_embed1-3, block1-3, norm1-3 + extra modules + 해당 FRM/FFM)
         3:  Freeze stages 0-3 (patch_embed1-4, block1-4, norm1-4 + extra modules + 해당 FRM/FFM)
         999: Freeze all including FRMs/FFMs (완전 전체 freeze)
         
        Args:
            freeze_fusion_with_stages: If True, freeze FRM/FFM along with corresponding stages
        """
        backbone = self.cmnext_model.backbone
        
        if self.frozen_stages == -1:
            # Unfreeze all - 모든 파라미터를 trainable로 설정
            print("🔥 Unfreezing all stages")
            for param in backbone.parameters():
                param.requires_grad = True
            return

        if self.frozen_stages == 999:
            # Freeze everything completely
            print("🧊 Freezing ALL parameters (including FRMs/FFMs)")
            for param in backbone.parameters():
                param.requires_grad = False
            backbone.eval()
            return
        
        # Stage별 freeze 수행
        num_stages = 4  # CMNext has 4 stages
        
        for stage_idx in range(min(self.frozen_stages + 1, num_stages)):
            print(f"🧊 Freezing stage {stage_idx}")
            
            # Freeze main patch embedding
            patch_embed_name = f"patch_embed{stage_idx + 1}"
            if hasattr(backbone, patch_embed_name):
                patch_embed = getattr(backbone, patch_embed_name)
                patch_embed.eval()
                for param in patch_embed.parameters():
                    param.requires_grad = False
                print(f"   - Frozen {patch_embed_name}")
            
            # Freeze main transformer blocks
            block_name = f"block{stage_idx + 1}"
            if hasattr(backbone, block_name):
                block = getattr(backbone, block_name)
                block.eval()
                for param in block.parameters():
                    param.requires_grad = False
                print(f"   - Frozen {block_name}")
            
            # Freeze main layer norm
            norm_name = f"norm{stage_idx + 1}"
            if hasattr(backbone, norm_name):
                norm = getattr(backbone, norm_name)
                norm.eval()
                for param in norm.parameters():
                    param.requires_grad = False
                print(f"   - Frozen {norm_name}")
            
            # Freeze extra modules (multimodal parts)
            if hasattr(backbone, 'extra_downsample_layers') and stage_idx < len(backbone.extra_downsample_layers):
                extra_downsample = backbone.extra_downsample_layers[stage_idx]
                extra_downsample.eval()
                for param in extra_downsample.parameters():
                    param.requires_grad = False
                print(f"   - Frozen extra_downsample_layers[{stage_idx}]")
            
            # Freeze extra blocks
            extra_block_name = f"extra_block{stage_idx + 1}"
            if hasattr(backbone, extra_block_name):
                extra_block = getattr(backbone, extra_block_name)
                extra_block.eval()
                for param in extra_block.parameters():
                    param.requires_grad = False
                print(f"   - Frozen {extra_block_name}")
            
            # Freeze extra norms
            extra_norm_name = f"extra_norm{stage_idx + 1}"
            if hasattr(backbone, extra_norm_name):
                extra_norm = getattr(backbone, extra_norm_name)
                extra_norm.eval()
                for param in extra_norm.parameters():
                    param.requires_grad = False
                print(f"   - Frozen {extra_norm_name}")
            
            # Freeze score predictors
            if hasattr(backbone, 'extra_score_predictor') and stage_idx < len(backbone.extra_score_predictor):
                score_predictor = backbone.extra_score_predictor[stage_idx]
                score_predictor.eval()
                for param in score_predictor.parameters():
                    param.requires_grad = False
                print(f"   - Frozen extra_score_predictor[{stage_idx}]")
            
            # Freeze corresponding FRM and FFM
            if freeze_fusion_with_stages:
                if hasattr(backbone, 'FRMs') and stage_idx < len(backbone.FRMs):
                    frm = backbone.FRMs[stage_idx]
                    frm.eval()
                    for param in frm.parameters():
                        param.requires_grad = False
                    print(f"   - Frozen FRMs[{stage_idx}]")
                
                if hasattr(backbone, 'FFMs') and stage_idx < len(backbone.FFMs):
                    ffm = backbone.FFMs[stage_idx]
                    ffm.eval()
                    for param in ffm.parameters():
                        param.requires_grad = False
                    print(f"   - Frozen FFMs[{stage_idx}]")
    
    def forward(self, x: List[torch.Tensor]) -> Tuple[torch.Tensor]:
        """Forward pass of CMNext backbone.
        
        Args:
            x: List of multimodal tensors [rgb_tensor, depth_tensor, event_tensor, lidar_tensor]
               Each tensor has shape (B, C, H, W)
        
        Returns:
            Tuple of feature tensors from different stages
        """
        # CMNext backbone expects list of multimodal inputs
        features = self.cmnext_model.backbone(x)
        
        # Convert to MMDetection standard format
        # features should be a list/dict with multi-scale outputs
        if isinstance(features, dict):
            # If features is dict with keys like '0', '1', '2', '3'
            outs = []
            for idx in self.out_indices:
                if str(idx) in features:
                    outs.append(features[str(idx)])
                elif idx in features:
                    outs.append(features[idx])
        elif isinstance(features, (list, tuple)):
            # If features is list/tuple
            outs = [features[i] for i in self.out_indices]
        else:
            raise ValueError(f"Unexpected features format: {type(features)}")
        
        return tuple(outs)
    
    def train(self, mode: bool = True):
        """Set train/eval mode."""
        super().train(mode)
        
        if mode and self.norm_eval:
            # Set norm layers to eval mode
            for m in self.modules():
                if isinstance(m, (nn.BatchNorm2d, nn.LayerNorm)):
                    m.eval()
    
    def init_weights(self):
        """Initialize weights of the backbone."""
        if self.init_cfg is None:
            # Apply custom weight initialization
            self.cmnext_model.apply(self.cmnext_model._init_weights)
        else:
            super().init_weights()



class Attention(nn.Module):
    def __init__(self, dim, head, sr_ratio):
        super().__init__()
        self.head = head
        self.sr_ratio = sr_ratio 
        self.scale = (dim // head) ** -0.5
        self.q = nn.Linear(dim, dim)
        self.kv = nn.Linear(dim, dim*2)
        self.proj = nn.Linear(dim, dim)

        if sr_ratio > 1:
            self.sr = nn.Conv2d(dim, dim, sr_ratio, sr_ratio)
            self.norm = nn.LayerNorm(dim)

    def forward(self, x: Tensor, H, W) -> Tensor:
        B, N, C = x.shape
        q = self.q(x).reshape(B, N, self.head, C // self.head).permute(0, 2, 1, 3)

        if self.sr_ratio > 1:
            x = x.permute(0, 2, 1).reshape(B, C, H, W)
            x = self.sr(x).reshape(B, C, -1).permute(0, 2, 1)
            x = self.norm(x)
            
        k, v = self.kv(x).reshape(B, -1, 2, self.head, C // self.head).permute(2, 0, 3, 1, 4)

        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)

        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        x = self.proj(x)
        return x


class DWConv(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dwconv = nn.Conv2d(dim, dim, 3, 1, 1, groups=dim)

    def forward(self, x: Tensor, H, W) -> Tensor:
        B, _, C = x.shape
        x = x.transpose(1, 2).view(B, C, H, W)
        x = self.dwconv(x)
        return x.flatten(2).transpose(1, 2)


class MLP(nn.Module):
    def __init__(self, c1, c2):
        super().__init__()
        self.fc1 = nn.Linear(c1, c2)
        self.dwconv = DWConv(c2)
        self.fc2 = nn.Linear(c2, c1)
        
    def forward(self, x: Tensor, H, W) -> Tensor:
        return self.fc2(F.gelu(self.dwconv(self.fc1(x), H, W)))


class PatchEmbed(nn.Module):
    def __init__(self, c1=3, c2=32, patch_size=7, stride=4, padding=0):
        super().__init__()
        self.proj = nn.Conv2d(c1, c2, patch_size, stride, padding)    # padding=(ps[0]//2, ps[1]//2)
        self.norm = nn.LayerNorm(c2)

    def forward(self, x: Tensor) -> Tensor:
        x = self.proj(x)
        _, _, H, W = x.shape
        x = x.flatten(2).transpose(1, 2)
        x = self.norm(x)
        return x, H, W

class PatchEmbedParallel(nn.Module):
    def __init__(self, c1=3, c2=32, patch_size=7, stride=4, padding=0, num_modals=4):
        super().__init__()
        self.proj = ModuleParallel(nn.Conv2d(c1, c2, patch_size, stride, padding))    # padding=(ps[0]//2, ps[1]//2)
        self.norm = LayerNormParallel(c2, num_modals)

    def forward(self, x: list) -> list:
        x = self.proj(x)
        _, _, H, W = x[0].shape
        x = self.norm(x)
        return x, H, W
    
class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    Copied from timm
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.
    """
    def __init__(self, p: float = None):
        super().__init__()
        self.p = p

    def forward(self, x: Tensor) -> Tensor:
        if self.p == 0. or not self.training:
            return x
        kp = 1 - self.p
        shape = (x.shape[0],) + (1,) * (x.ndim - 1)
        random_tensor = kp + torch.rand(shape, dtype=x.dtype, device=x.device)
        random_tensor.floor_()  # binarize
        return x.div(kp) * random_tensor
    
class Block(nn.Module):
    def __init__(self, dim, head, sr_ratio=1, dpr=0., is_fan=False):
        super().__init__()
        self.norm1 = nn.LayerNorm(dim)
        self.attn = Attention(dim, head, sr_ratio)
        self.drop_path = DropPath(dpr) if dpr > 0. else nn.Identity()
        self.norm2 = nn.LayerNorm(dim)
        self.mlp = MLP(dim, int(dim*4)) if not is_fan else ChannelProcessing(dim, mlp_hidden_dim=int(dim*4))

    def forward(self, x: Tensor, H, W) -> Tensor:
        x = x + self.drop_path(self.attn(self.norm1(x), H, W))
        x = x + self.drop_path(self.mlp(self.norm2(x), H, W))
        return x


class ChannelProcessing(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, attn_drop=0., drop_path=0., mlp_hidden_dim=None, norm_layer=nn.LayerNorm):
        super().__init__()
        assert dim % num_heads == 0, f"dim {dim} should be divided by num_heads {num_heads}."
        self.dim = dim
        self.num_heads = num_heads

        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.mlp_v = MLP(dim, mlp_hidden_dim)
        self.norm_v = norm_layer(dim)

        self.q = nn.Linear(dim, dim, bias=qkv_bias)
        self.pool = nn.AdaptiveAvgPool2d((None, 1))
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x, H, W, atten=None):
        B, N, C = x.shape

        v = x.reshape(B, N, self.num_heads, C // self.num_heads).permute(0, 2, 1, 3)
        q = self.q(x).reshape(B, N, self.num_heads, C // self.num_heads).permute(0, 2, 1, 3)
        k = x.reshape(B, N, self.num_heads,  C // self.num_heads).permute(0, 2, 1, 3)

        q = q.softmax(-2).transpose(-1,-2)
        _, _, Nk, Ck  = k.shape
        k = k.softmax(-2)
        k = torch.nn.functional.avg_pool2d(k, (1, Ck))
        
        attn = self.sigmoid(q @ k)

        Bv, Hd, Nv, Cv = v.shape
        v = self.norm_v(self.mlp_v(v.transpose(1, 2).reshape(Bv, Nv, Hd*Cv), H, W)).reshape(Bv, Nv, Hd, Cv).transpose(1, 2)
        x = (attn * v.transpose(-1, -2)).permute(0, 3, 1, 2).reshape(B, N, C)
        return x 


class PredictorConv(nn.Module):
    def __init__(self, embed_dim=384, num_modals=4):
        super().__init__()
        self.num_modals = num_modals
        self.self_scorers = nn.ModuleList([SpatialAttentionModule(embed_dim) for _ in range(num_modals)])
        self.score_nets = nn.ModuleList([nn.Sequential(
            nn.Conv2d(embed_dim, embed_dim, 3, 1, 1, groups=(embed_dim)),
            nn.Conv2d(embed_dim, 1, 1),
            nn.Sigmoid()
        )for _ in range(num_modals)])

    def forward(self, x):
        B, C, H, W = x[0].shape
        final_scores = [torch.zeros((B, 1, H, W), device=x[0].device) for _ in range(self.num_modals)]
        for i in range(self.num_modals):
            self_attention_map = self.self_scorers[i](x[i])
            content_score = self.score_nets[i](x[i])
            final_scores[i] = self_attention_map * content_score
        return final_scores

class ModuleParallel(nn.Module):
    def __init__(self, module):
        super(ModuleParallel, self).__init__()
        self.module = module

    def forward(self, x_parallel):
        return [self.module(x) for x in x_parallel]

class ConvLayerNorm(nn.Module):
    """Channel first layer norm
    """
    def __init__(self, normalized_shape, eps=1e-6) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.ones(normalized_shape))
        self.bias = nn.Parameter(torch.zeros(normalized_shape))
        self.eps = eps

    def forward(self, x: Tensor) -> Tensor:
        u = x.mean(1, keepdim=True)
        s = (x - u).pow(2).mean(1, keepdim=True)
        x = (x - u) / torch.sqrt(s + self.eps)
        x = self.weight[:, None, None] * x + self.bias[:, None, None]
        return x

class LayerNormParallel(nn.Module):
    def __init__(self, num_features, num_modals=4):
        super(LayerNormParallel, self).__init__()
        # self.num_modals = num_modals
        for i in range(num_modals):
            setattr(self, 'ln_' + str(i), ConvLayerNorm(num_features, eps=1e-6))

    def forward(self, x_parallel):
        return [getattr(self, 'ln_' + str(i))(x) for i, x in enumerate(x_parallel)]


cmnext_settings = {
    # 'B0': [[32, 64, 160, 256], [2, 2, 2, 2]],
    # 'B1': [[64, 128, 320, 512], [2, 2, 2, 2]],
    'B2': [[64, 128, 320, 512], [3, 4, 6, 3]],
    # 'B3': [[64, 128, 320, 512], [3, 4, 18, 3]],
    'B4': [[64, 128, 320, 512], [3, 8, 27, 3]],
    'B5': [[64, 128, 320, 512], [3, 6, 40, 3]]
}


class CMNeXtPSP(nn.Module):
    def __init__(self, model_name: str = 'B0', modals: list = ['rgb', 'depth', 'event', 'lidar']):
        super().__init__()
        self.iter = 0
        self._has_logged_this_epoch = False

        assert model_name in cmnext_settings.keys(), f"Model name should be in {list(cmnext_settings.keys())}"
        embed_dims, depths = cmnext_settings[model_name]
        
        self.modals = modals[1:] if len(modals) > 1 else []
        self.num_modals = len(self.modals)
        drop_path_rate = 0.1
        norm_cfg = dict(type='BN', requires_grad=True)

        # ✅ [최종 수정] 모든 스테이지별 모듈을 nn.ModuleList로 묶어 관리 (리팩토링)
        self.patch_embeds = nn.ModuleList()
        self.blocks = nn.ModuleList()
        self.norms = nn.ModuleList()
        
        if self.num_modals > 0:
            self.extra_downsample_layers = nn.ModuleList()
            self.extra_blocks = nn.ModuleList()
            self.extra_norms = nn.ModuleList()
            self.FRMs = nn.ModuleList()
            self.FFMs = nn.ModuleList()
        
        if self.num_modals > 1:
            self.extra_score_predictor = nn.ModuleList([
                PredictorConv(embed_dims[i], self.num_modals) for i in range(len(depths))
            ])
            
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, sum(depths))]
        cur = 0
        num_heads = [1, 2, 5, 8]

        for i in range(4): # 4개의 스테이지
            self.patch_embeds.append(PatchEmbed(
                c1=3 if i == 0 else embed_dims[i-1], c2=embed_dims[i],
                patch_size=7 if i == 0 else 3, stride=4 if i == 0 else 2,
                padding=7//2 if i == 0 else 3//2))
            
            self.blocks.append(nn.ModuleList([
                Block(embed_dims[i], num_heads[i], sr_ratio=[8,4,2,1][i], dpr=dpr[cur + j]) for j in range(depths[i])]))
            
            self.norms.append(nn.LayerNorm(embed_dims[i]))
            cur += depths[i]

            if self.num_modals > 0:
                self.extra_downsample_layers.append(PatchEmbedParallel(
                    c1=3 if i == 0 else embed_dims[i-1], c2=embed_dims[i],
                    patch_size=7 if i == 0 else 3, stride=4 if i == 0 else 2,
                    padding=7//2 if i == 0 else 3//2, num_modals=self.num_modals))
                
                self.extra_blocks.append(nn.ModuleList([
                    MSPABlock(embed_dims[i], mlp_ratio=[8,8,4,4][i], drop_path=dpr[cur-depths[i]+j], norm_cfg=norm_cfg) for j in range(depths[i])]))
                
                self.extra_norms.append(ConvLayerNorm(embed_dims[i]))
                self.FRMs.append(FRM(dim=embed_dims[i], reduction=1))
                self.FFMs.append(FFM(dim=embed_dims[i], reduction=1, num_heads=num_heads[i], norm_layer=nn.BatchNorm2d))
        self.visualization_buffer = {}
    
                
    def visualize_normalized_inputs(self, batch_tensor: List[torch.Tensor], modality_names: List[str], save_path='normalized_inputs.png'):
        """모델에 들어가는 정규화된 입력 텐서를 시각화합니다."""
        # batch_tensor는 [rgb_tensor, depth_tensor, intensity_tensor] 형태의 리스트
        import cv2
        import matplotlib.pyplot as plt
        sample_idx = 0  # 첫 번째 샘플을 확인
        
        # 각 모달리티 텐서에서 첫 번째 샘플 추출
        samples = [tensor[sample_idx].cpu() for tensor in batch_tensor]

        fig, axes = plt.subplots(1, len(samples), figsize=(5 * len(samples), 5))
        if len(samples) == 1:
            axes = [axes]

        for i, (tensor, name) in enumerate(zip(samples, modality_names)):
            # (C, H, W) -> (H, W, C)
            # 채널이 3개가 아니면 첫 채널만 시각화
            if tensor.shape[0] != 3:
                img_data = tensor[0] 
                cmap = 'viridis' # 단일 채널은 컬러맵으로 표현
            else:
                img_data = tensor.permute(1, 2, 0)
                cmap = None
                
            # 픽셀 값을 [0, 1] 범위로 클리핑하여 시각화
            img_data = torch.clamp(img_data, 0, 1)

            axes[i].imshow(img_data, cmap=cmap)
            axes[i].set_title(f"{name}\nmin: {tensor.min():.2f}, max: {tensor.max():.2f}, mean: {tensor.mean():.2f}")
            axes[i].axis('off')

        plt.tight_layout()
        plt.savefig(save_path)
        plt.close()
        print(f"✅ 정규화된 입력 시각화 완료: {save_path}")
        
    def tokenselect2(self, x_ext: List[Tensor], module: nn.Module) -> Tuple[Tensor, List[Tensor], Tensor]:
        """
        [개선된 Soft Mix + 로깅 버전]
        기존 soft mix 로직을 유지하면서, 각 모달리티의 기여도를 담고 있는
        attention_weights 맵을 추가로 반환합니다.
        """
        x_scores = module(x_ext)
        stacked_scores = torch.cat(x_scores, dim=1)
        attention_weights = F.softmax(stacked_scores, dim=1)
        stacked_features = torch.stack(x_ext, dim=1)
        weighted_features = stacked_features * attention_weights.unsqueeze(2)
        x_f = torch.sum(weighted_features, dim=1)
        return x_f, x_scores, attention_weights
    
    def forward(self, x: list) -> list:
        x_cam_input = x[0]
        x_ext_input_list = x[1:] if self.num_modals > 0 else []
        B = x_cam_input.shape[0]
        outs = []
        for i in range(4):
            x_cam, H, W = self.patch_embeds[i](x_cam_input)
            for blk in self.blocks[i]:
                x_cam = blk(x_cam, H, W)
            x_cam_out = self.norms[i](x_cam).reshape(B, H, W, -1).permute(0, 3, 1, 2)
            
            if self.num_modals > 0:
                x_ext_embedded, _, _ = self.extra_downsample_layers[i](x_ext_input_list)
                x_f, x_scores, attention_weights = self.tokenselect2(x_ext_embedded, self.extra_score_predictor[i]) if self.num_modals > 1 else (x_ext_embedded[0], None, None)
                for blk in self.extra_blocks[i]:
                    x_f = blk(x_f)
                x_f_processed = self.extra_norms[i](x_f)
                
                x_cam_rect, x_f_rect = self.FRMs[i](x_cam_out, x_f_processed)
                x_fused = self.FFMs[i](x_cam_rect, x_f_rect)
        
                if not self.training and not self.visualization_buffer:
                    self.visualization_buffer[f'stage_{i+1}'] = {
                        'attention_weights': attention_weights.detach() if attention_weights is not None else None,
                        'scores': x_scores,
                        'rgb_feature': x_cam_out.detach(),
                        'fused_aux_feature': x_f_processed.detach(),
                        'final_fused_feature': x_fused.detach()
                    }
                outs.append(x_fused)
                x_cam_input = x_fused
                x_ext_input_list = [x.reshape(B, H, W, -1).permute(0, 3, 1, 2) + x_f_rect for x in x_ext_embedded] if self.num_modals > 1 else [x_f_rect]
            else:
                outs.append(x_cam_out)
                x_cam_input = x_cam_out
                
        return outs
    
    
class CMNeXtPSPShuffled0213(CMNeXtPSP):
    """
    CMNeXtPSP를 상속받아 forward 메서드의 입력 순서만 변경하는 클래스.
    """
    def __init__(self, model_name: str = 'B0', modals: list = ['rgb', 'depth', 'event', 'lidar']):
        # 부모 클래스(CMNeXtPSP)의 __init__ 메서드를 그대로 호출하여
        # 모든 t 변수와 레이어를 초기화합니다.
        super().__init__(model_name=model_name, modals=modals)

    def forward(self, x: list) -> list:
        """
        입력 순서를 [0, 2, 1, 3]으로 재배치한 후,
        부모 클래스의 원래 forward 로직을 실행합니다.
        """
        # ✅ 입력 리스트 x의 순서를 [0, 2, 1, 3]으로 재배치
        if len(x) == 4:
            x = [x[0], x[2], x[1], x[3]]
        
        # 순서가 바뀐 x를 사용하여 부모 클래스의 forward 메서드를 호출
        return super().forward(x)
    
    
class CMNeXtPSPShuffled0132(CMNeXtPSP):
    """
    CMNeXtPSP를 상속받아 forward 메서드의 입력 순서만 변경하는 클래스.
    """
    def __init__(self, model_name: str = 'B0', modals: list = ['rgb', 'depth', 'event', 'lidar']):
        # 부모 클래스(CMNeXtPSP)의 __init__ 메서드를 그대로 호출하여
        # 모든 변수와 레이어를 초기화합니다.
        super().__init__(model_name=model_name, modals=modals)

    def forward(self, x: list) -> list:
        """
        입력 순서를 [0, 2, 1, 3]으로 재배치한 후,
        부모 클래스의 원래 forward 로직을 실행합니다.
        """
        # ✅ 입력 리스트 x의 순서를 [0, 2, 1, 3]으로 재배치
        if len(x) == 4:
            x = [x[0], x[1], x[3], x[2]]
        
        # 순서가 바뀐 x를 사용하여 부모 클래스의 forward 메서드를 호출
        return super().forward(x)